# Dependabot configuration for MCP Server Template
# Monitors dependencies in the template itself and hook files

version: 2
updates:
  # Monitor template-level dependencies (hooks, development tools)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Rome"
    labels:
      - "dependencies"
      - "template-core"
    reviewers:
      - "pietroperona"  # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      include: "scope"
        
  # Monitor GitHub Actions (if you add CI/CD workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Rome"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "pietroperona"  # Replace with your GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"